### ISSUE TITLE
Add "Tag Dataset" Button in NL Workbench Project Details View

### ISSUE THREAD

**Issue by jkarpala** [247aitools/nlworkbench-ui#11]
From feedback from a user:

> Previously, there was a button that said "Tag Dataset" underneath the dataset in the attached screenshot.
> Now, the only way to tag the dataset is to right click on the Project on the left-side panel or the dataset Name in the main field. This is not an intuitive place to find the "Tag Dataset" button. Since this is such a high-volume option, the button should be displayed more prominently and accessibly in the main field of the page.
> - Tony

my initial idea: possibly add another column to the grid and add the main action button there? so if not transformed, transform button, and if it is transformed tag button? if you have a better idea go with that.

**Comment by 247manish** [comment]
So, right click is not-intuitive then?

**Comment by jkarpala** [comment]
I think the actions on right click are good, and should stay, just the main actions should probably be more accessible.

**Comment by jkarpala** [comment]
actually, we'll need to come up with a way of tagging multiple datasets at once, maybe we can start some of the design here? since we'll eventually have to let them select multiple, maybe change the grid to allow the selections and just have a tag button at the bottom? right now they can only select one, but once we implement the merged view they can select multiple?

**Comment by 247manish** [comment]
To me, it becomes a single dataset for the user. So, truly it kinda is "Tag Project". It doesn't make sense for us to give them the ability to be able to tag specific datasets but show them the merged view. This defeats the merged concept. If datasets are merged, they are merged for tagging as well. Otherwise, whats wrong with todays ability. With giving them ability to select one or more datasets to tag separately might create issues and confusion. 

Also, on the tagging view we have a filter to show untagged text strings which now will come from multiple datasets. With the column specifying and be able to sort by dataset-name, will give them the ability to tag specific strings for a dataset or collectively bulk tag similar text strings with same intent across multiple datasets.

Again we can discuss this in a meeting with them but we should keep it simple.

**Comment by jkarpala** [comment]
so your idea is just have one big tag project button on the screen, and then if they want in the tagging screen to filter by dataset they can? think of the dataset as just a filtering method and not a full separation?

**Comment by 247manish** [comment]
Just brainstorming about how can we still keep things simple and focused. I am fine with giving them checkboxes on the project details page where we will list datasets with a single tag button. If they don't select any datasets, then nothing gets selected to be tagged. If they want to see all untagged text strings from all datasets (because there will be common strings to bulk tag), the will end up selecting all datasets all the time which kinda is Tag Project. I don't mean to label the button as "Tag Project", may be it should just be "Tag".

**Comment by Travmatolog** [comment]
For now i just made dataset name to be a link to tag page.
I think it is better to add "Tag datasets" button on project details page which will lead to "tag all" datasets page.
On the "tag all" page i think we should create a component that will show a list of datasets where you can select/unselect a dataset user wants to work with. In that way user will always aware with which dataset(s) he is working and can change selection "on the fly".

**Comment by Travmatolog** [comment]
The button is back.
